name: build-extract-actions
run-name: Building Extract after push by ${{ github.actor }}
on: [push]
jobs:
    build-extract:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: maven
            - run: mvn -q package -DskipTests=true --batch-mode
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: java-app
                  path: '/home/runner/work/extract/extract/extract/target/*.war'

    test-extract:
        needs: build-extract
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v3
             - uses: actions/setup-java@v3
               with:
                   distribution: 'temurin'
                   java-version: '17'
                   cache: maven
             - uses: browser-actions/setup-chrome@v1
             - name: Download artifact generated in build job
               uses: actions/download-artifact@v3
               with:
                   name: java-app
                   path: /tmp/extract.war
             - uses: isbang/compose-action@v1.5.0
               with:
                   compose-file: "./docker-compose-test.yaml"
             - name: Execute unit tests
               run: mvn -q clean test -Punit-tests --batch-mode --fail-at-end
             - name: Execute integration tests
               run: mvn -q clean verify -Pintegration-tests --batch-mode
             - name: Execute functional tests
               run: mvn -q failsafe:integration-test -Pfunctional-tests --batch-mode
            # - name: "Publishes test results"
            #    if: success() || failure()
            #    uses: scacap/action-surefire-report@v1
