name: build-extract-actions
run-name: Building Extract after push by ${{ github.actor }}
on: [push]
jobs:
    build-extract:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ $matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - run: mvn -B package
