name: build-extract-actions
run-name: Building Extract after push by ${{ github.actor }}
on: [push]
jobs:
    build-extract:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: maven
            - run: mvn -B package -DskipTests=true
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: java-app
                  path: '$/target/*.war'

    test-extract:
        needs: build-extract
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v3
             - uses: actions/setup-java@v3
                   with:
                   distribution: 'temurin'
                   java-version: '17'
                   cache: maven
             - name: Download artifact generated in build job
               uses: actions/upload-artifact@v2
               with:
                   name: java-app
                   path: /tmp/extract.war
             - uses: isbang/compose-action@v1.5.0
               with:
                   compose-file: "./docker-compose-test.yml"
             - run: mvn clean test
